source "byLuke/setKeyTool.mel";
source "byLuke/cpScaleKeywithLayer.mel";
select -r SK_C8010_rig:FKHead_M ;
$selsA=`ls -sl`;
select -r SK_C8010_rig:FKRing1_M SK_C8010_rig:FKRing2_M SK_C8010_rig:FKRing3_M SK_C8010_rig:FKRing4_M ;
$selsB=`ls -sl`;
$ly="ly_ring";
if(`objExists $ly`)delete $ly;
animLayer $ly;
select -r $selsB;
animLayer -e  -addSelectedObjects $ly;

cpKeywithLayer("ly_ring", $selsA[0], "tx", $selsB[0], "tx", -4, -0.5,0);
cpKeywithLayer("ly_ring", $selsA[0], "tx", $selsB[1], "tx", -2, -0.55,0);
cpKeywithLayer("ly_ring", $selsA[0], "tx", $selsB[2], "tx", 0, -0.65,0);
cpKeywithLayer("ly_ring", $selsA[0], "tx", $selsB[3], "tx", 2, -0.8,0);

cpScaleKeywithLayerXYZ("scale_ly",$selsA[0],$selsB[0],-1,0.8,0,2);
cpScaleKeywithLayerXYZ("scale_ly",$selsA[0],$selsB[1],0,0.75,0,2);
cpScaleKeywithLayerXYZ("scale_ly",$selsA[0],$selsB[2],0,0.6,0,2);
cpScaleKeywithLayerXYZ("scale_ly",$selsA[0],$selsB[3],1,0.4,0,2);