batchExportSelectedFBX();
proc batchExportSelectedFBX(){
    string $sn = `file -q -sn`;
    string $dir = `match "^.*/" $sn`;
    string $dirF=($dir+"fbx");
    $work=`file -q -ex $dirF`;
    if($work==1){
        $sels=`ls -sl`;    
        string $obj;
        
        for($i=0;$i<`size($sels)`;$i++){
            $obj=$sels[$i];
            select -r $obj;
            //print ($obj+("\n"));
            file -force -options "v=0;" -typ "FBX export" -pr -es ($dirF+"/"+$obj);
            }
    }else{
        print ("§ä¤£¨ì:"+$dirF);
    }
    }