/*改小數點後幾位的工具 --lv1--lp0--rc0
	函數(input ,取小數點以下幾位)
	*/
global proc float decimalChange(float $in,int $n){           
	int $scale =`pow 10 $n`;
	return (`trunc ($in*$scale)`)/$scale;
	}

/*求b可以被a除幾次 --lv1--lp0--rc1
	*/
global proc int sqrtM(int $a,int $b){
    int $times;    
    if ($b>=$a){         
        $times=sqrtM($a,($b/$a));
        $times=$times+1;
    }else{
        $times=0;
        }

    return $times;
    }

/*去掉重複的float元素 --lv1--lp1--rc1
	*/
global proc float[] floatArrayRemoveDuplicates(float $array[],int $x){
   /*帝龜法*/
    $n=size($array);    
    if ($x>=$n-1){
        return $array;
    }else{
        floatArrayRemoveDuplicates($array,($x+1));
        for($i=($x+1);$i<$n;$i++){
            if($array[$x]==$array[$i])
                floatArrayRemoveAtIndex($i, $array);
            }
        return $array;
        }
    }

/*合併兩個float array --lv1--lp1--rc0
	*/
global proc float[] floatArrayCatenate(float $array1[],float $array2[]){
	float $array3[];
	for ($item1 in $array1)
		{
		$array3[size($array3)] = $item1;
		}
	for ($item2 in $array2)
		{
		$array3[size($array3)] = $item2;
		}
	return $array3;
	}



global proc int[] intArrayRemoveDuplicates(int $array[], int $x){

    $n=size($array); 
    if ($x>=$n-1){
        return $array; 
    }else{
        intArrayRemoveDuplicates($array, ($x+1)); 
        for($i=($x+1);$i<$n;$i++){ 
            if($array[$x]==$array[$i]) 
				intArrayRemoveAtIndex($i, $array);
            }    
        return $array;
        }
    }
    
/*--lvl--lpl--rco
*/
global proc int[] intArrayCatenate(int $array1[], int $array2[]) {
    int $array3[]; 
    for ($item1 in $array1) { 
        $array3[(`size($array3)`)] = $item1; 
        }
    for ($item2 in $array2) { 
        $array3[(`size($array3)`)] = $item2; 
        } 
    return $array3;
    }

	
/*加減平均浮點數 --lv1--lp0--rc0
	0:plus
	1:minus
	2:averange
	*/	
global proc float[] plusMnusAverageFloat(int $mode,float $vA[],float $vB[]){

	float $v[];
	if(`size($vA)`==`size($vB)`){
		switch($mode) {
		
			case 0:
				for($i=0;$i<`size($vA)`;$i++){
					$v[$i]=$vA[$i]+$vB[$i];
					}
				break;
			case 1:
				for($i=0;$i<`size($vA)`;$i++){			
				$v[$i]=$vA[$i]-$vB[$i];
				}
				break;	
			case 2:
				for($i=0;$i<`size($vA)`;$i++){			
				$v[$i]=($vA[$i]+$vB[$i])/2;
				}
				break;	
			default:
				break;
			}
	}else{
		print("兩組數量不一致");
		}
	return $v;
	}

/*開根號的mel(from cgsociety) --lv1--lp0--rc0
	*/
global proc float rad(float $number, float $root) {
             float $conversion = 1.0/$root;
             float $result = `pow $number $conversion`;
             return $result;
  }
  
/*求立方根 --lv2--lp0--rc0
	*/
global proc float getCubeRoot(float $X,float $Y,float $Z){
        $V=rad((`pow $X 2`+`pow $Y 2`+`pow $Z 2`),3);
        return $V;
        }

/*求平方根 --lv2--lp0--rc0
	*/
global proc float getSqRoot(float $X,float $Y){
        $V=sqrt(`pow $X 2`+`pow $Y 2`);
        return $V;
        }	

/*取最大 --lv1 --lp0 --rc1
$max=getMax($vArray,0,$vArray[0]);
print $max;
*/	
global proc float getMax(float $vArray[],int $i,float $max){
	//float $max;
	$i=$i+1;
	if($vArray[$i]>$max)
		$max=$vArray[$i];
	if($i<`size($vArray)`-1)
		$max=getMax($vArray,$i,$max);
	
	return $max;
	}

/*取最小 --lv1 --lp0 --rc1
$min=getMin($vArray,0,$vArray[0]);
print $min;
*/	
global proc float getMin(float $vArray[],int $i,float $min){
	//float $max;
	$i=$i+1;
	if($vArray[$i]<$min)
		$min=$vArray[$i];
	if($i<`size($vArray)`-1)
		$min=getMin($vArray,$i,$min);
	
	return $min;
	}	
		
/*複數平均浮點數 --lv1--lp1--rc0
	*/
global proc float multiAverageFloat(float $array[]){
	float $v=0;
	$n=size($array);
	for($i in $array){
		$v=$v+$i;
		}
	$v=$v/$n;
	return $v;
	}		
		
/*等分浮點數 --lv1--lp0--rc0
*/
global proc float[] arrangeFloatString(float $nums[]){
    $n = size($nums)-1; 
    $d=($nums[$n]-$nums[0])/$n;
    for($i=1;$i<$n;$i++){
        $nums[$i]=($nums[0]+($d*$i));
        }
    print $d;    
    return $nums;
    };