//Maya Preference 2023 (Release 1)
//
//

optionVar -version 3;

// RecentFiles
optionVar -cat "RecentFiles"
 -sa "RecentFilesList"
 -sva "RecentFilesList" "X:/Art/1_Assets/3_Animation/MAYA/Player/Bow/BowAttackMove/ANI_Player_Bow_AttackMoveF_001_v01.mb"
 -sva "RecentFilesList" "X:/Art/1_Assets/3_Animation/MAYA/Player/Bow/BowAttackMove/ANI_Player_Bow_AttackMoveFL_001_v01.mb"
 -sva "RecentFilesList" "X:/Art/1_Assets/3_Animation/MAYA/Player/Bow/BowAttackMove/ANI_Player_Bow_AttackMoveFR_001_v01.mb"
 -sva "RecentFilesList" "X:/Art/1_Assets/3_Animation/MAYA/Player/Bow/BowAttackMove/ANI_Player_Bow_AttackMoveL_001_v01.mb"
 -sva "RecentFilesList" "X:/Art/1_Assets/3_Animation/MAYA/Player/Bow/BowAttackMove/ANI_Player_Bow_AttackMoveR_001_v01.mb"
 -sva "RecentFilesList" "X:/Art/1_Assets/3_Animation/MAYA/Player/Bow/BowAttackMove/all.ma"
 -sva "RecentFilesList" "X:/Art/1_Assets/3_Animation/MAYA/Player/Bow/BowAttackMove/ANI_Player_Bow_AttackMoveB_001_v01.mb"
 -sva "RecentFilesList" "X:/Art/1_Assets/3_Animation/MAYA/Player/Bow/ANI_Player_Bow_Attack_001_v01.mb"
 -sva "RecentFilesList" "X:/Art/1_Assets/3_Animation/MAYA/TEST.mb"
 -sva "RecentFilesList" "C:/Users/luke/Downloads/center_ground_0417.ma"
 -sa "RecentFilesTypeList"
 -sva "RecentFilesTypeList" "mayaBinary"
 -sva "RecentFilesTypeList" "mayaBinary"
 -sva "RecentFilesTypeList" "mayaBinary"
 -sva "RecentFilesTypeList" "mayaBinary"
 -sva "RecentFilesTypeList" "mayaBinary"
 -sva "RecentFilesTypeList" "mayaAscii"
 -sva "RecentFilesTypeList" "mayaBinary"
 -sva "RecentFilesTypeList" "mayaBinary"
 -sva "RecentFilesTypeList" "mayaBinary"
 -sva "RecentFilesTypeList" "mayaAscii"
 -sa "RecentProjectsList"
 -sva "RecentProjectsList" "C:/Projects/Treeverse/Maya"
 -sva "RecentProjectsList" "Z:/Art/1_Assets/3_Animation"
 -sva "RecentProjectsList" "X:/Art/1_Assets/3_Animation"
 -sva "RecentProjectsList" "X:/Art/1_Assets/3_Animation/MAYA"
 ;

