//Maya Preference 2023 (Release 1)
//
//

optionVar -version 3;

// RecentFiles
optionVar -cat "RecentFiles"
 -sa "RecentFilesList"
 -sva "RecentFilesList" "G:/¦@¥Î¶³ºÝµwºÐ/Endless Clouds Shared/Art/1_Assets/2_Rig/SkinnedMeshes/Enemies/WildAnimal/SK_Enemy_HornOwl/SK_Enemy_HornOwl_rigging.ma"
 -sva "RecentFilesList" "X:/Art/1_Assets/1_Models/SkinnedMeshes/Player/Bip/Armor_001/SK_Player_Armor_001.mb"
 -sva "RecentFilesList" "Z:/Art/1_Assets/2_Rig/SkinnedMeshes/Player/Bip/SM_Player_Armor_001_bind.mb"
 -sva "RecentFilesList" "C:/Projects/EndlessClouds/Maya/scenes/Character/Player/Player_Armor01_Rigging.mb"
 -sva "RecentFilesList" "Z:/Art/1_Assets/2_Rig/SkinnedMeshes/Player/Bip/SM_Player_Armor_001_bind_v03.mb"
 -sva "RecentFilesList" "Z:/Art/1_Assets/2_Rig/SkinnedMeshes/Player/Bip/SM_Player_Armor_001_bind_v02.mb"
 -sva "RecentFilesList" "Z:/Art/1_Assets/2_Rig/SkinnedMeshes/Player/Bip/SM_Player_Armor_001_bind_v02_t.mb"
 -sva "RecentFilesList" "Z:/Art/1_Assets/2_Rig/SkinnedMeshes/Player/Acs/Cloak/SK_Player_Armor01_Cloak_bind.mb"
 -sva "RecentFilesList" "Z:/Art/1_Assets/2_Rig/SkinnedMeshes/Player/Acs/Hatchet/SK_Player_Weapon_Hatchet_bind.mb"
 -sva "RecentFilesList" "Z:/Art/1_Assets/3_Animation/02_Enemy/07_SK_Enemy_DireWolf/maya/Enemy_DireWolf_Skill_v03.ma"
 -sa "RecentFilesTypeList"
 -sva "RecentFilesTypeList" "mayaAscii"
 -sva "RecentFilesTypeList" "mayaBinary"
 -sva "RecentFilesTypeList" "mayaBinary"
 -sva "RecentFilesTypeList" "mayaBinary"
 -sva "RecentFilesTypeList" "mayaBinary"
 -sva "RecentFilesTypeList" "mayaBinary"
 -sva "RecentFilesTypeList" "mayaBinary"
 -sva "RecentFilesTypeList" "mayaBinary"
 -sva "RecentFilesTypeList" "mayaBinary"
 -sva "RecentFilesTypeList" "mayaAscii"
 -sa "RecentProjectsList"
 -sva "RecentProjectsList" "C:/Projects/Treeverse/Maya"
 ;

