//Maya Preference 2023 (Release 1)
//
//

optionVar -version 3;

// RecentFiles
optionVar -cat "RecentFiles"
 -sa "RecentFilesList"
 -sva "RecentFilesList" "Z:/Art/1_Assets/3_Animation/MAYA/Player/Main/Test/Test_Player_GreatSword_Attack_002_v18.mb"
 -sva "RecentFilesList" "Z:/Art/1_Assets/3_Animation/MAYA/Player/Main/Test/Test_Player_GreatSword_Attack_003_v18.mb"
 -sva "RecentFilesList" "Z:/Art/1_Assets/3_Animation/MAYA/Player/Main/Test/temp/Test_Player_GreatSword_Attack_003_export.mb"
 -sva "RecentFilesList" "Z:/Art/1_Assets/3_Animation/MAYA/Player/Main/Test/Test_Player_GreatSword_Attack_001_v18.mb"
 -sva "RecentFilesList" "Z:/Art/1_Assets/2_Rig/SkinnedMeshes/Player/Bip/Armor/SK_Player_Armor_001/test01_anchorParentWorld.mb"
 -sva "RecentFilesList" "Z:/Art/1_Assets/3_Animation/MAYA/Player/Main/TestA/TestA_Player_GreatSword_Attack_003_v18.mb"
 -sva "RecentFilesList" "Z:/Art/1_Assets/3_Animation/MAYA/Player/Main/TestA/ANI_Player_GreatSword_Dead_001_v02.mb"
 -sva "RecentFilesList" "Z:/Art/1_Assets/2_Rig/SkinnedMeshes/Player/Bip/Armor/SK_Player_Armor_001/test02_allJtParentWorld.mb"
 -sva "RecentFilesList" "Z:/Art/1_Assets/3_Animation/MAYA/Player/Main/Test02/Test02_Player_GreatSword_Attack_001_v18.mb"
 -sva "RecentFilesList" "Z:/Art/1_Assets/2_Rig/SkinnedMeshes/Player/Bip/Armor/SK_Player_Armor_001/test03_twolayerAnchor.mb"
 -sa "RecentFilesTypeList"
 -sva "RecentFilesTypeList" "mayaBinary"
 -sva "RecentFilesTypeList" "mayaBinary"
 -sva "RecentFilesTypeList" "mayaBinary"
 -sva "RecentFilesTypeList" "mayaBinary"
 -sva "RecentFilesTypeList" "mayaBinary"
 -sva "RecentFilesTypeList" "mayaBinary"
 -sva "RecentFilesTypeList" "mayaBinary"
 -sva "RecentFilesTypeList" "mayaBinary"
 -sva "RecentFilesTypeList" "mayaBinary"
 -sva "RecentFilesTypeList" "mayaBinary"
 -sa "RecentProjectsList"
 -sva "RecentProjectsList" "C:/Projects/Treeverse/Maya"
 -sva "RecentProjectsList" "Z:/Art/1_Assets/3_Animation"
 -sva "RecentProjectsList" "X:/Art/1_Assets/3_Animation"
 ;

